[package]
name = "mimalloc"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"

[workspace]
members = ["mimalloc-sys"]

[dependencies]
mimalloc-sys = { path = "mimalloc-sys", version = "0.1.0" }

[dev-dependencies]
mockalloc = "0.1"
