[package]
name = "mimalloc-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["mimalloc-sys"]

[dependencies]
mimalloc-sys = { path = "mimalloc-sys", version = "0.1.0" }

[dev-dependencies]
mockalloc = "0.1"
